### ISSUE TITLE
[BUG] closeOnClick not working because of 'touchstart'

### ISSUE THREAD

**Issue by xxRockOnxx** [vfreitas-/growl-alert#2]
Looked at the `growl-alert` source in my `node_modules` and saw that the addEventListener has `'click touchstart'`

After removing `touchstart` from the listener it is now working.

Now when I looked at the `src` from the one I forked, I don't see any `touchstart` there even after building it. Where did that come from?

**Comment by lemuelflores** [comment]
@vfreitas- Please update the release. Found out npm was using the old one. Thanks!

**Comment by vfreitas-** [comment]
I did a refactor on this lib a few weeks ago, that's why the npm is outdated. Sadly I got a lot of work to do in the past few weeks so I couldn't release the new version yet.

I'll update it soon, thanks!
